version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myDataBasePwd
      - MYSQL_PASSWORD=mySqlPwd
      - MYSQL_USER=user
      - MYSQL_DATABASE=database